
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 3GB
      max-request-size: 3GB
  data:
    redis:
      host: 192.168.74.131
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
      timeout: 10s
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
minio:
  endpoint: http://192.168.74.131:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket:
    test: test
    answer: answer
